services:

  kms:
      build:
        context: .
        dockerfile: Dockerfile
      command: ["./kms", "a"]
      depends_on:
        kms_db:
          condition: service_healthy  # Wait for db to be healthy
      networks:
        - kms-network

  kms_db:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: YourStrongPassword
      MYSQL_DATABASE: KeyStorage
      MYSQL_USER: kms
      MYSQL_PASSWORD: YourStrongPassword
    networks:
      - kms-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "kms", "-pYourStrongPassword"]
      interval: 10s
      timeout: 5s
      retries: 10

networks:
  kms-network:
    driver: bridge